name: to_dp_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.1

  #SQL
  sqflite: ^2.3.2
  path_provider: ^2.1.2
  path: 1.8.3

  #BLOC
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5

  #ICON LAUNCH
  flutter_launcher_icons: ^0.13.1

  #  notification


  #screen
  flutter_screenutil: ^5.9.0

  #api
  retrofit: '>=4.0.0 <5.0.0'
  logger: any

  json_annotation: ^4.8.1

  #DI
  get_it: ^7.6.7
  injectable: ^2.3.5

  #SVG
  flutter_svg: ^2.0.10+1

  #one signal
  onesignal_flutter: ^5.1.3

  #http
  http: ^1.2.0



flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/todo.png"


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  json_serializable: ^6.7.1
  retrofit_generator: '>=7.0.0 <8.0.0'
  build_runner: '^2.4.8'
  flutter_gen_runner: ^5.4.0
  injectable_generator: ^2.3.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: DancingFont
      fonts:
        - asset: assets/fonts/DancingScript-Regular.ttf

flutter_gen:
  integrations:
    flutter_svg: true
  